name: Bundle installation
on: push

jobs:
    integration-tests:
        name: Installation in Symfony ${{ matrix.symfony }} with PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: ['7.3', '7.4', '8.0', '8.1']
                symfony: ['4.4', '5.0', '5.1', '5.2', '5.3', '5.4', '6.0', '6.1']
                exclude:
                    - php: '8.0'
                      symfony: '5.0'
                    - php: '8.1'
                      symfony: '5.0'
                      # see https://github.com/symfony/symfony/issues/44081
                    - php: '8.1'
                      symfony: '5.2'
                    - php: '7.3'
                      symfony: '6.0'
                    - php: '7.4'
                      symfony: '6.0'
                    - php: '7.3'
                      symfony: '6.1'
                    - php: '7.4'
                      symfony: '6.1'
                    - php: '8.0'
                      symfony: '6.1'

        steps:
            # Setup
            -   name: Checkout
                uses: actions/checkout@v2
                with:
                    path: 'project'

            -   name: PHP setup
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: mbstring, xml, ctype, iconv, intl
                    coverage: xdebug

            # Install symfony app
            -   name: Create Symfony app
                run: |
                    composer create-project --no-install symfony/skeleton:"${{ matrix.symfony }}.*" app
                    composer config -d ./app repositories.messenger-azure-bundle path ../project
                    composer config -d ./app minimum-stability dev
                    composer config -d ./app --no-interaction allow-plugins.symfony/flex true
                    composer install -d ./app
            # Cache Composer dependencies
            -   name: Get composer cache directory
                id: composer-cache
                run: echo "::set-output name=dir::$(composer config -d ./app cache-files-dir)"

            -   name: Cache dependencies
                uses: actions/cache@v1
                with:
                    path: ${{ steps.composer-cache.outputs.dir }}
                    key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
                    restore-keys: ${{ runner.os }}-composer-

            # Install the bundle
            -   name: Install AymdevMessengerAzureBundle
                run: composer require -d ./app --prefer-source aymdev/messenger-azure-bundle:"*"